-- Add Russian name column and populate English + Russian translations for all NAS accounts
-- Migration 315 set the `name` column to Uzbek but did not update name_en or add name_ru

ALTER TABLE accounts ADD COLUMN IF NOT EXISTS name_ru VARCHAR(255);

-- Populate name_en and name_ru for NAS accounts based on code
UPDATE accounts SET
    name_en = CASE code
        -- Fixed assets
        WHEN '0100' THEN 'Fixed Assets'
        WHEN '0110' THEN 'Land'
        WHEN '0120' THEN 'Buildings and Structures'
        WHEN '0130' THEN 'Machinery and Equipment'
        WHEN '0140' THEN 'Furniture and Office Equipment'
        WHEN '0150' THEN 'Computer Equipment'
        WHEN '0160' THEN 'Vehicles'
        WHEN '0200' THEN 'Depreciation of Fixed Assets'
        WHEN '0220' THEN 'Depreciation of Buildings'
        WHEN '0230' THEN 'Depreciation of Machinery'
        WHEN '0260' THEN 'Depreciation of Vehicles'
        WHEN '0400' THEN 'Intangible Assets'
        WHEN '0410' THEN 'Patents, Licenses, Know-how'
        WHEN '0420' THEN 'Trademarks'
        WHEN '0430' THEN 'Organizational Expenses'
        WHEN '0490' THEN 'Amortization of Intangible Assets'
        WHEN '0810' THEN 'Capital Investments in Progress'
        -- Inventory
        WHEN '1010' THEN 'Raw Materials and Supplies'
        WHEN '1020' THEN 'Purchased Semi-finished Products'
        WHEN '1030' THEN 'Fuel'
        WHEN '1040' THEN 'Containers and Packaging'
        WHEN '1050' THEN 'Spare Parts'
        WHEN '1060' THEN 'Construction Materials'
        WHEN '1080' THEN 'Agricultural Products'
        WHEN '1090' THEN 'Other Materials'
        -- Production
        WHEN '2010' THEN 'Main Production'
        WHEN '2310' THEN 'Auxiliary Production'
        WHEN '2510' THEN 'Overhead Production Costs'
        WHEN '2590' THEN 'Machine Hour Costs'
        WHEN '2610' THEN 'Defective Product Losses'
        WHEN '2810' THEN 'Finished Goods'
        WHEN '2910' THEN 'Goods for Resale'
        -- Deferred
        WHEN '3100' THEN 'Deferred Expenses'
        WHEN '3110' THEN 'Deferred Expenses (Long-term)'
        -- Receivables
        WHEN '4010' THEN 'Accounts Receivable'
        WHEN '4020' THEN 'Inter-division Receivables'
        WHEN '4210' THEN 'Employee Advances'
        WHEN '4310' THEN 'Advances for Inventory'
        WHEN '4320' THEN 'Advances for Long-term Assets'
        WHEN '4410' THEN 'Prepaid Taxes (Input VAT)'
        WHEN '4710' THEN 'Accountable Persons'
        WHEN '4790' THEN 'Other Receivables'
        WHEN '4800' THEN 'Long-term Receivables'
        WHEN '4910' THEN 'Allowance for Doubtful Debts'
        -- Cash
        WHEN '5010' THEN 'Cash Register'
        WHEN '5020' THEN 'Foreign Currency Cash'
        WHEN '5030' THEN 'Cash in Transit'
        WHEN '5110' THEN 'Settlement Account'
        WHEN '5210' THEN 'Special Bank Accounts'
        WHEN '5510' THEN 'Deposit Certificates'
        WHEN '5520' THEN 'Short-term Bonds'
        -- Payables
        WHEN '6010' THEN 'Suppliers and Contractors'
        WHEN '6015' THEN 'Goods Received, Not Invoiced'
        WHEN '6016' THEN 'Goods Delivered, Not Invoiced'
        WHEN '6020' THEN 'Inter-division Payables'
        WHEN '6110' THEN 'Advances Received'
        WHEN '6210' THEN 'Short-term Bank Loans'
        WHEN '6220' THEN 'Short-term Borrowings'
        WHEN '6310' THEN 'Deferred Revenue'
        WHEN '6410' THEN 'Tax Liabilities'
        WHEN '6420' THEN 'VAT Payable'
        WHEN '6430' THEN 'Income Tax Payable'
        WHEN '6510' THEN 'Social Insurance Contributions'
        WHEN '6520' THEN 'Insurance Payable'
        WHEN '6710' THEN 'Wages Payable'
        WHEN '6810' THEN 'Short-term Bank Credits'
        WHEN '6990' THEN 'Other Payables'
        WHEN '6920' THEN 'Interest Payable'
        -- Long-term liabilities
        WHEN '7310' THEN 'Long-term Advances Received'
        WHEN '7810' THEN 'Long-term Bank Credits'
        WHEN '7820' THEN 'Long-term Borrowings'
        -- Equity
        WHEN '8300' THEN 'Charter Capital'
        WHEN '8310' THEN 'Common Shares'
        WHEN '8400' THEN 'Reserve Capital'
        WHEN '8500' THEN 'Additional Capital'
        WHEN '8600' THEN 'Targeted Funds'
        WHEN '8700' THEN 'Retained Earnings'
        WHEN '8710' THEN 'Retained Earnings (Prior Years)'
        WHEN '8720' THEN 'Declared Dividends'
        -- Revenue
        WHEN '9010' THEN 'Revenue from Finished Goods'
        WHEN '9020' THEN 'Revenue from Goods Sales'
        WHEN '9030' THEN 'Revenue from Services'
        WHEN '9040' THEN 'Revenue from Construction Contracts'
        WHEN '9110' THEN 'Cost of Finished Goods Sold'
        WHEN '9120' THEN 'Cost of Goods Sold'
        WHEN '9130' THEN 'Production Costs'
        WHEN '9140' THEN 'General Production Costs'
        WHEN '9150' THEN 'Cost of Services'
        WHEN '9160' THEN 'Cost of Construction Works'
        WHEN '9210' THEN 'Gain on Sale of Fixed Assets'
        WHEN '9220' THEN 'Gain on Sale of Other Assets'
        WHEN '9310' THEN 'Other Operating Income'
        WHEN '9320' THEN 'Free Received Property'
        WHEN '9340' THEN 'Prior Years Operations Income'
        WHEN '9350' THEN 'Written-off Payables'
        WHEN '9410' THEN 'Period Expenses'
        WHEN '9420' THEN 'Salary Expenses'
        WHEN '9430' THEN 'Rent Expenses'
        WHEN '9440' THEN 'Utility Expenses'
        WHEN '9450' THEN 'Office Expenses'
        WHEN '9460' THEN 'Insurance Expenses'
        WHEN '9470' THEN 'Depreciation Expenses'
        WHEN '9480' THEN 'Advertising and Marketing'
        WHEN '9490' THEN 'Professional Services'
        WHEN '9495' THEN 'Travel and Representation'
        WHEN '9510' THEN 'Interest Income'
        WHEN '9540' THEN 'Foreign Exchange Gain'
        WHEN '9610' THEN 'Interest Expenses'
        WHEN '9620' THEN 'Bank Service Charges'
        WHEN '9630' THEN 'Foreign Exchange Loss'
        WHEN '9690' THEN 'Other Financial Expenses'
        WHEN '9710' THEN 'Loss on Sale of Fixed Assets'
        WHEN '9720' THEN 'Loss on Sale of Other Assets'
        WHEN '9810' THEN 'Extraordinary Losses'
        WHEN '9820' THEN 'Income Tax Expense'
        WHEN '9910' THEN 'Final Financial Result'
        WHEN '9920' THEN 'Current Year Profit'
        ELSE name_en
    END,
    name_ru = CASE code
        -- Fixed assets
        WHEN '0100' THEN 'Основные средства'
        WHEN '0110' THEN 'Земля'
        WHEN '0120' THEN 'Здания и сооружения'
        WHEN '0130' THEN 'Машины и оборудование'
        WHEN '0140' THEN 'Мебель и офисное оборудование'
        WHEN '0150' THEN 'Компьютерное оборудование'
        WHEN '0160' THEN 'Транспортные средства'
        WHEN '0200' THEN 'Износ основных средств'
        WHEN '0220' THEN 'Износ зданий'
        WHEN '0230' THEN 'Износ машин и оборудования'
        WHEN '0260' THEN 'Износ транспортных средств'
        WHEN '0400' THEN 'Нематериальные активы'
        WHEN '0410' THEN 'Патенты, лицензии, ноу-хау'
        WHEN '0420' THEN 'Товарный знак'
        WHEN '0430' THEN 'Организационные расходы'
        WHEN '0490' THEN 'Амортизация нематериальных активов'
        WHEN '0810' THEN 'Незавершённые капитальные вложения'
        -- Inventory
        WHEN '1010' THEN 'Сырьё и материалы'
        WHEN '1020' THEN 'Покупные полуфабрикаты'
        WHEN '1030' THEN 'Топливо'
        WHEN '1040' THEN 'Тара и тарные материалы'
        WHEN '1050' THEN 'Запасные части'
        WHEN '1060' THEN 'Строительные материалы'
        WHEN '1080' THEN 'Сельхозпродукция'
        WHEN '1090' THEN 'Прочие материалы'
        -- Production
        WHEN '2010' THEN 'Основное производство'
        WHEN '2310' THEN 'Вспомогательное производство'
        WHEN '2510' THEN 'Общепроизводственные расходы'
        WHEN '2590' THEN 'Расходы машино-часов'
        WHEN '2610' THEN 'Потери от брака'
        WHEN '2810' THEN 'Готовая продукция'
        WHEN '2910' THEN 'Товары для перепродажи'
        -- Deferred
        WHEN '3100' THEN 'Расходы будущих периодов'
        WHEN '3110' THEN 'Расходы будущих периодов (долгосрочные)'
        -- Receivables
        WHEN '4010' THEN 'Счета к получению'
        WHEN '4020' THEN 'Внутренние расчёты с подразделениями'
        WHEN '4210' THEN 'Авансы сотрудникам'
        WHEN '4310' THEN 'Авансы за ТМЦ'
        WHEN '4320' THEN 'Авансы за долгосрочные активы'
        WHEN '4410' THEN 'Авансовые платежи в бюджет (НДС входящий)'
        WHEN '4710' THEN 'Подотчётные лица'
        WHEN '4790' THEN 'Прочая дебиторская задолженность'
        WHEN '4800' THEN 'Долгосрочная дебиторская задолженность'
        WHEN '4910' THEN 'Резерв по сомнительным долгам'
        -- Cash
        WHEN '5010' THEN 'Касса'
        WHEN '5020' THEN 'Валютная касса'
        WHEN '5030' THEN 'Денежные переводы в пути'
        WHEN '5110' THEN 'Расчётный счёт'
        WHEN '5210' THEN 'Специальные банковские счета'
        WHEN '5510' THEN 'Депозитные сертификаты'
        WHEN '5520' THEN 'Краткосрочные облигации'
        -- Payables
        WHEN '6010' THEN 'Поставщики и подрядчики'
        WHEN '6015' THEN 'Товары получены, счёт не выставлен'
        WHEN '6016' THEN 'Товары отгружены, счёт не выставлен'
        WHEN '6020' THEN 'Внутренние расчёты с подразделениями'
        WHEN '6110' THEN 'Полученные авансы'
        WHEN '6210' THEN 'Краткосрочные банковские кредиты'
        WHEN '6220' THEN 'Краткосрочные займы'
        WHEN '6310' THEN 'Доходы будущих периодов'
        WHEN '6410' THEN 'Задолженность по налогам'
        WHEN '6420' THEN 'НДС к уплате'
        WHEN '6430' THEN 'Налог на прибыль к уплате'
        WHEN '6510' THEN 'Отчисления в социальные фонды'
        WHEN '6520' THEN 'Страховые платежи'
        WHEN '6710' THEN 'Задолженность по оплате труда'
        WHEN '6810' THEN 'Краткосрочные банковские кредиты'
        WHEN '6990' THEN 'Прочая кредиторская задолженность'
        WHEN '6920' THEN 'Задолженность по процентам'
        -- Long-term liabilities
        WHEN '7310' THEN 'Долгосрочные полученные авансы'
        WHEN '7810' THEN 'Долгосрочные банковские кредиты'
        WHEN '7820' THEN 'Долгосрочные займы'
        -- Equity
        WHEN '8300' THEN 'Уставный капитал'
        WHEN '8310' THEN 'Обыкновенные акции'
        WHEN '8400' THEN 'Резервный капитал'
        WHEN '8500' THEN 'Добавочный капитал'
        WHEN '8600' THEN 'Целевые поступления'
        WHEN '8700' THEN 'Нераспределённая прибыль'
        WHEN '8710' THEN 'Нераспределённая прибыль прошлых лет'
        WHEN '8720' THEN 'Объявленные дивиденды'
        -- Revenue
        WHEN '9010' THEN 'Выручка от реализации готовой продукции'
        WHEN '9020' THEN 'Выручка от продажи товаров'
        WHEN '9030' THEN 'Выручка от оказания услуг'
        WHEN '9040' THEN 'Выручка по строительным контрактам'
        WHEN '9110' THEN 'Себестоимость реализованной готовой продукции'
        WHEN '9120' THEN 'Себестоимость проданных товаров'
        WHEN '9130' THEN 'Производственные расходы'
        WHEN '9140' THEN 'Общепроизводственные расходы'
        WHEN '9150' THEN 'Себестоимость услуг'
        WHEN '9160' THEN 'Себестоимость строительных работ'
        WHEN '9210' THEN 'Прибыль от продажи основных средств'
        WHEN '9220' THEN 'Прибыль от продажи прочих активов'
        WHEN '9310' THEN 'Прочие операционные доходы'
        WHEN '9320' THEN 'Безвозмездно полученное имущество'
        WHEN '9340' THEN 'Прибыль от операций прошлых лет'
        WHEN '9350' THEN 'Списание кредиторской задолженности'
        WHEN '9410' THEN 'Расходы периода'
        WHEN '9420' THEN 'Расходы на оплату труда'
        WHEN '9430' THEN 'Расходы на аренду'
        WHEN '9440' THEN 'Коммунальные расходы'
        WHEN '9450' THEN 'Офисные расходы'
        WHEN '9460' THEN 'Расходы на страхование'
        WHEN '9470' THEN 'Расходы на амортизацию'
        WHEN '9480' THEN 'Реклама и маркетинг'
        WHEN '9490' THEN 'Профессиональные услуги'
        WHEN '9495' THEN 'Командировочные и представительские'
        WHEN '9510' THEN 'Процентные доходы'
        WHEN '9540' THEN 'Доходы от курсовой разницы'
        WHEN '9610' THEN 'Процентные расходы'
        WHEN '9620' THEN 'Расходы на банковские услуги'
        WHEN '9630' THEN 'Убытки от курсовой разницы'
        WHEN '9690' THEN 'Прочие финансовые расходы'
        WHEN '9710' THEN 'Убыток от продажи основных средств'
        WHEN '9720' THEN 'Убыток от продажи прочих активов'
        WHEN '9810' THEN 'Чрезвычайные убытки'
        WHEN '9820' THEN 'Расходы по налогу на прибыль'
        WHEN '9910' THEN 'Итоговый финансовый результат'
        WHEN '9920' THEN 'Прибыль текущего года'
        ELSE name_ru
    END
WHERE deleted_at IS NULL;
